01 HOME
05 REM SPEED=185
10 PRINT "HELLO! THIS DISK CONTAINS A NUMBER OF"
20 PRINT "PROGRAMS FOR MESSING WITH SCREEN OUTPUT"
30 PRINT "- BOTH AS YOU ARE TYPING IT, AND FROM"
40 PRINT "PROGRAM AND COMMAND OUTPUT."
50 PRINT
60 PRINT "NOTE THAT REGARDLESS OF WHAT THE SCREEN"
70 PRINT "SHOWS, THE REAL INPUT THAT YOUR APPLE"
80 PRINT "SEES WILL BE EXACTLY WHAT YOU TYPED!"
100 PRINT
110 PRINT "TO TRY ONE OF THE OUTPUT FILTERS, USE:"
120 PRINT "  ] BRUN FILTER"
130 PRINT "TO RETURN OUTPUT TO NORMAL, ENTER:"
140 PRINT "  ] PR#0"
150 PRINT "OR RESTART BASIC WITH CONTROL-RESET"
160 PRINT
200 PRINT "SEE THE SOURCES USED TO CREATE THIS"
205 PRINT "DISK, AT"
210 PRINT "HTTPS://GITHUB.COM/MICAHCOWAN/FNORD"
215 PRINT
220 PRINT "HAVE FUN!"
225 REM SPEED=255
230 END
