01 HOME
05 SPEED=185
10 PRINT "HELLO! THIS DISK CONTAINS A NUMBER OF"
20 PRINT "PROGRAMS FOR MESSING WITH SCREEN OUTPUT"
30 PRINT "- BOTH AS YOU ARE TYPING IT, AND FROM"
40 PRINT "PROGRAM AND COMMAND OUTPUT."
50 PRINT
60 PRINT "NOTE THAT ALTHOUGH WHAT YOU'RE TYPING"
70 PRINT "APPEARS TO CHANGE, THE REAL INPUT THAT"
80 PRINT "YOUR APPLE SEES WILL BE EXACTLY WHAT"
90 PRINT "YOU TYPED!"
100 PRINT
110 PRINT "TO TRY ONE OF THE OUTPUT FILTERS, USE:"
120 PRINT "  ] BRUN FILTER"
130 PRINT "TO RETURN OUTPUT TO NORMAL, ENTER:"
140 PRINT "  ] PR#0"
150 PRINT "OR RESTART BASIC WITH CONTROL-RESET"
160 PRINT
170 PRINT "HERE'S AN EXAMPLE OF SOME OUTPUTS:"
180 PRINT "  ] BRUN MIXCASE"
185 PRINT CHR$(4);"BRUN MIXCASE"
190 PRINT "HUH! SOME WEIRD OUTPUT GOING ON HERE"
195 PRINT CHR$(4);"PR#0"
200 PRINT "  ] BRUN HLSPACES"
205 PRINT CHR$(4);"BRUN HLSPACES"
210 PRINT "BUT THIS AT LEAST IS QUITE READABLE."
215 PRINT CHR$(4);"PR#0"
220 PRINT "HAVE FUN!"
225 SPEED=255
230 END
